[package]
name = "mailrs"
version = "0.1.0"
edition = "2021"

license = "GPL-3.0-only"
description = "a notmuch GUI/TUI mail client"

[dependencies]
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"
