[package]
name = "mailrs"
version = "0.1.0"
edition = "2021"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

license = "GPL-2.0-only"

[dependencies]
dioxus = { version = "0.6.0", features = ["launch", "fullstack", "desktop", "router"] }
dioxus-logger = "0.6.0"
