import { VerticalBox, HorizontalBox } from "std-widgets.slint";

import { Facade } from "global.slint";
import { Boxes } from "boxes.slint";
import { Commander } from "commander.slint";
import { MBox } from "structs.slint";

export { Facade, MBox }

enum Page {
    boxes,
}

component MainContent inherits Rectangle {
    property <Page> active-page: Page.boxes;

    HorizontalBox {
        alignment: center;

        Boxes {
            visible: active-page == Page.boxes;
        }
    }
}

component WelcomePage inherits VerticalLayout {
    HorizontalBox {
        alignment: center;
    }
}

export component AppWindow inherits Window {
    title: "mailrs";

    min-width: 512px;
    min-height: 320px;
    preferred-width: 1200px;
    preferred-height: 640px;

    VerticalLayout {
        spacing: 5px;
        width: parent.width;

        MainContent {
            background: red;
            width: parent.width;
            visible: Facade.mboxes.length != 0;

            Text {
                text: "main, " + Facade.mboxes.length;
            }
        }

        if (Facade.mboxes.length == 0): WelcomePage { }

        Commander {
            background: blue;
            max-height: 5cm;
            preferred-height: 1cm;
            width: parent.width;
            visible: true;
        }
    }
}
