import { TabWidget, VerticalBox, ListView } from "std-widgets.slint";

import { Message, Tag } from "structs.slint";
import { Facade } from "global.slint";
import { MessageList } from "list/message.slint";

import { HorizontalListView } from "widgets/widgets.slint";

export component MBox inherits Rectangle {
    in-out property <string> title;
    in-out property <[Message]> messages;

    width: 100%;
    height: 100%;

    VerticalBox {
        MessageList {
            messages: messages;
        }
    }
}

// Boxes is a meta-object that contains all the opened boxes
//
// Showing a header column that contains the name of the box (or the query)
// and a "body" that contains the list of messages
export component Boxes inherits Rectangle {
    in-out property <int> focused_box: 0;
    width: 100%;
    height: 100%;

    MBox {
        title: Facade.mboxes[focused_box].query;
        messages: Facade.mboxes[focused_box].messages;
    }
}

