import { TabWidget, StandardTableView, ScrollView } from "std-widgets.slint";

import { Message, Tag } from "structs.slint";
import { Facade } from "global.slint";

import { HorizontalListView } from "widgets/widgets.slint";

export component TagList inherits Rectangle {
    in-out property <[Tag]> tags;

    HorizontalLayout {
        for tag in tags: Rectangle {
            Text {
                text: tag.name;
            }
        }
    }
}

export component MBox inherits Rectangle {
    in-out property <string> title;
    in-out property <[Message]> messages;

    width: 100%;
    height: 100%;

    ScrollView {
        width: 100%;
        height: 100%;

        viewport-width: parent.width;
        viewport-height: parent.height;

        scrolled() => {
            debug("viewport-x: ", self.viewport-x);
            debug("viewport-y: ", self.viewport-y);
        }

        Rectangle {
            width: 100%;
            height: 100%;
            background: green;

            HorizontalLayout {
                width: 100%;
                height: 100%;
                Rectangle {
                    width: 100%;
                    height: 100%;
                    Text {
                        text: "Message ID";
                    }
                }

                Rectangle {
                    Text {
                        text: "Tags";
                    }
                }
            }
        }

        for message in messages: Rectangle {
            HorizontalLayout {
                Rectangle {
                    Text {
                        text: message.id;
                    }
                }

                Rectangle {
                    TagList {
                        tags: message.tags;
                    }
                }
            }
        }
    }


}

// Boxes is a meta-object that contains all the opened boxes
//
// Showing a header column that contains the name of the box (or the query)
// and a "body" that contains the list of messages
export component Boxes inherits Rectangle {
    in-out property <int> focused_box: 0;

    MBox {
        title: Facade.mboxes[focused_box].query;
        messages: Facade.mboxes[focused_box].messages;
    }
}

