name: Deploy Docs to GitHub Pages
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  release:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: mailrs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build documentation
        run: nix --print-build-logs build .#mailrs-doc --show-trace
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./result/share/doc
          keep_files: true
